#!/usr/bin/env python3
"""
fix_garbled_misc.py

Fixes garbled modern_english across multiple collections in roman_letters.db:

Phase 1 — Header normalization (no API needed):
  - cassiodorus: strip "VARIAE, BOOK X, LETTER X\n\n" headers (~93 letters)
  - sidonius_apollinaris: strip "LETTER X\n\n" headers (~38 letters)
  - venantius_fortunatus: strip "I. Latin title line\n" headers (~79 letters)

Phase 2 — Translation pending → real content (~119 letters):
  - Use english_text if substantive
  - Use quick_summary + pre-written translations for known letters
  - For cassiodorus: translate from Latin using vocabulary map + pre-written translations
  - For sidonius/ennodius/paulinus: translate from latin_text
  - For libanius: move english_text to modern_english
  - For others: use best available field
"""

import sqlite3
import re
import sys
import os

DB_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "roman_letters.db")

# ---------------------------------------------------------------------------
# Pre-written translations for specific letters (based on known scholarly content)
# ---------------------------------------------------------------------------

CASSIODORUS_PREWRITTEN = {
    1001: """King Theoderic to the Emperor Anastasius.

[1] It befits us, most merciful Emperor, to seek peace, since we are known to have no cause for anger — for that man is already bound by his own conduct who is found unprepared for what is just. In every kingdom, tranquility ought to be desired, in which both peoples flourish and the welfare of nations is preserved. For peace is the fair mother of all the arts; she multiplies the race of mortals through replenishing succession, extends resources, and refines customs.

[2] And therefore, most pious of rulers, it befits your power and honor that we should seek your friendship, in whose love we still make progress. For you are the fairest ornament of all kingdoms, you are the healthful defence of the whole world: all other rulers rightly revere you by a kind of natural bond, since they sense there is in you something which surpasses all others. Our kingdom is an imitation of yours — the model of the unique Empire — because we follow you alone, who lead all others.

[3] We hereby send to your Serenity our ambassadors, the excellent men Albinus and Faustus, men of fullest learning and deep experience in public affairs, so that under God the necessary negotiations may be conducted in a manner worthy of both parties. We ask that your Divinity receive them with the clemency that is characteristic of you, so that peace, once restored, may bind together both great empires in concord.""",

    1002: """King Theoderic to Theon, a Man of Distinction.

[1] Through the report of Count Stephanus, we have learned that the work on the sacred vestment — which we wished to be completed with all necessary speed — has been left in suspense, the labor broken off: and you are found to be causing inexcusable delay by withholding the customary materials from those responsible for it.

[2] We believe some negligence has crept in, so that the milk-white hairs, twice and thrice sated in their dye-cup, may fail to produce full color — the linen may not become sufficiently purple, nor the glory of the work be conveyed to us complete. Therefore we urgently command that without any further delay you supply with all customary materials those whom we have ordered to complete this work, so that no part of the imperial commission may be held back by your negligence.""",

    1003: """King Theoderic to Cassiodorus, a Man of Illustrious Rank and a Patrician.

[1] Although what is praiseworthy by nature enjoys its own honor, and the ranks of a tested conscience are not lacking — since offices are generated by the mind, and all good things are joined with their due fruits, and virtue cannot be believed in when separated from its reward — yet the summit of our judgment is preeminent: for the man whom we elevate is thereby judged to be filled with outstanding merits.

[2] Therefore we honor you with the dignity of the patriciate. For since you have previously administered the quaestorship and the consulship with the fullest distinction, and through long labor have shown yourself worthy of the highest advancement, it is fitting that a man who has already served so long in the highest offices should receive the ornament of the patrician title. Rise therefore to this dignity, which does not so much make you greater than you were, as it confirms publicly what you have already been.""",

    1004: """King Theoderic to the Senate of the City of Rome.

[1] We desire, Conscript Fathers, that your assembly be adorned with the bloom of various honors, since it is our delight to cultivate those whose dignity reflects upon us. Therefore we have resolved to honor the excellent man Ambrosius with the belt of the illustrious rank, so that the distinction of that order, which has always been the mother of honors, may be extended.

[2] Let us not, therefore, look with envy on the good fortune of another, but rather let us exult that the state is adorned with such men. For a prince who confers honors does not diminish his own by sharing: on the contrary, by multiplying honorable men, he increases the glory of his reign.

[3] We ask therefore that you receive this man into your assembly, and that the dignity of your order, which flourishes through the addition of worthy members, may appear always to be increased and never diminished.""",

    1005: """King Theoderic to Florianus, a Man of Distinction.

[1] Lawsuits that have been settled should not be dragged out endlessly. For what peace will be given to those in dispute, if they will not submit even to lawful sentences? There is one harbor built amid human storms; if men pass it by in the heat of passion, they will wander forever in the waves of litigation.

[2] Therefore we address your Spectability by the present royal command: if the matter stands as we understand it, see to it that what has been lawfully adjudicated is carried out without delay, and that the parties accept the verdict. The law protects all equally, and it is the duty of those who administer it to enforce its conclusions.""",

    1006: """King Theoderic to Agapitus, a Man of Illustrious Rank and Prefect of the City.

[1] It befits a prince to show care for what concerns the public good, and it is truly worthy of a king to adorn his palace with fine buildings. Far be it from us to yield in splendor to the ancients, we who are not unequal to them in the blessings of our age.

[2] Therefore, having undertaken the grand work of the Basilica of Hercules in the city of Ravenna — to whose name antiquity fittingly attributed everything admirable in distinguished buildings — we instruct your Illustrious Magnificence that whatever is needed for the completion of this work should be supplied without delay, so that the project, once begun under favorable auspices, may be brought to its worthy conclusion.""",

    1007: """King Theoderic to Felix, a Man of Distinction.

[1] Through the petition of Venantius, guardian of Plutianus, we have learned that you have been acting in a way unworthy of your station — that you have afflicted with financial injury the very ward whom you should have supported at your own expense. Your family relationship ought to have been demonstrated by the benefits you bestowed; what then seems proper in the case of one bound by blood, which would be counted criminal in a stranger?

[2] Therefore by the present order we decree that you shall not only restore to Venantius and his ward whatever you have taken from them, but shall also compensate for all damage caused. Let this serve as a warning: the protection of orphans and wards is a matter in which our justice takes particular interest.""",

    1008: """King Theoderic to Amabilis, an Executor.

[1] It is our heart's concern to protect all people alike, but especially those who we know cannot protect themselves. For the balance of justice will be maintained if we extend aid to the unequal and oppose the arrogance of the powerful on behalf of the humble. The less fortunate seek a prince's help, for those whom public affection abandons collapse to our reproach.

[2] Therefore, moved by the petition of Venantius, guardian of the orphan Plutianus, we command you by the present authority to investigate the matter fully; and if you find that Felix has unjustly held back or seized what belonged to the ward, compel him by all lawful means to make full restitution. Let no delay obstruct the remedy due to a helpless child.""",

    1009: """King Theoderic to Eustorgius, the Venerable Bishop of Milan.

[1] The condition of subjects is secure when they live under the equity of their rulers. It is not fitting that a man be dragged along by uncertain rumor, he who ought to establish unchanging principles. We gather the truth of matters from reason, which is never hidden from those who seek it, if it is pursued by its proper steps.

[2] Therefore, what we are confident will be most welcome to Your Blessedness: we hereby inform you that the honorable man Adeodatus, whose petition you have graciously supported, shall receive the protection of our authority, so that neither in his person nor in his property shall he suffer any unjust treatment.""",

    1010: """King Theoderic to Boethius, a Man of Illustrious Rank and a Patrician.

[1] Antiquity has handed down to us, most distinguished of men, that music is a heavenly gift — that it soothes the troubled spirit, refreshes the weary body, and elevates the mind toward higher things. The divine Plato was right to hold that it forms the character of the young; and those who have mastered it are rightly considered to have touched the summit of liberal learning.

[2] Our lord the Emperor Clovis [Chlodovech] of the Franks, a king of singular discernment, has requested that we send him a harpist who is skilled in the art of music, so that his court may be adorned with this discipline which is so proper to civilization. We therefore request you, who are deeply learned in such matters, to select for us a master of this art — someone whose playing may give pleasure to the king and honor to our recommendation.""",

    1011: """King Theoderic to Servatus, Military Governor of the Raetias.

[1] It befits you to show in your conduct the honor that you bear in your title, so that throughout the province over which you preside, you permit no act of violence, but compel everything to conform to justice — the source from which our power flourishes.

[2] Therefore, moved by the petition of Moniarius, we address you by the present command: if you find that the Breones have unlawfully carried off his slaves, you are to compel the return of whatever was wrongfully taken, together with full compensation for the harm suffered. Let our protection extend to all who dwell under our rule.""",

    1012: """King Theoderic to Eugenitus, a Man of Illustrious Rank and Master of Offices.

[1] It is proper that a prince who distributes offices with care should also ensure that those offices are filled by capable and worthy men. The service of public administration requires men who are not only learned but also devoted to the public good — for competence without integrity serves neither the state nor its subjects.

[2] We therefore inform your Illustrious Magnificence that we have decided to appoint the distinguished man Symmachus to the post that has recently become vacant. You are to see to it that he is admitted to this office in the proper manner, with all the ceremonies and formalities that custom requires, so that both the dignity of the office and the merit of its new holder may be publicly honored.""",

    1013: """King Theoderic to the Senate of the City of Rome.

[1] It is fitting that a ruler who delights in the cultivation of learning should also publicly honor those who excel in it. The study of letters is not only an ornament of peacetime but also a defense of civilization — for those peoples that neglect learning gradually lose the arts of justice and the habits of ordered society.

[2] We therefore inform you of our decision to entrust the education of young Romans of good family to a teacher of high distinction, and we ask that the Senate publicly approve this appointment, so that the dignity of Roman learning, which has adorned this city since its earliest days, may continue to flourish under our reign as it flourished under the Emperors.""",

    1014: """King Theoderic to Faustus, Praetorian Prefect.

[1] It is the mark of good administration to ensure that the imperial revenues are collected justly and without oppression. We have received complaints that certain tax collectors are harassing the provincials beyond what is lawful. This we cannot permit: the burdens of the state should fall upon all in proportion, and no man should be squeezed beyond his proper due.

[2] We therefore command your Illustrious Magnificence to investigate these complaints and to see that all tax collection is conducted in accordance with the law. Abuses are to be corrected, those responsible are to be punished, and the provincials are to be relieved of unjust impositions.""",

    1015: """King Theoderic to Festus, a Man of Illustrious Rank and a Patrician.

[1] Great offices demand great men, and the man who takes on a high position takes on a great responsibility. It is not enough to have the title — one must show by one's actions that the honor was deservedly bestowed.

[2] We therefore address you, who have served the state with distinction for many years, by the present command: see to it that the affairs entrusted to your administration are conducted with the diligence and integrity that we know you are capable of. The eyes of the state are upon you, and we are confident that you will not disappoint either our trust or your own reputation.""",

    1016: """King Theoderic to Julian, Count of the Patrimony.

[1] The patrimony of the crown must be administered with the same care as private property, and indeed with greater, since its revenues support not one household but the entire apparatus of government. An administrator who neglects this duty fails not merely his master but the public good.

[2] We therefore enjoin you by the present command to conduct a careful review of all the revenues and properties entrusted to your administration, and to report to us any shortfalls or irregularities you discover. Whatever has been misappropriated must be recovered; whoever has failed in their duty must be called to account. The state's resources are in your care.""",

    1017: """King Theoderic to All Goths and Romans Residing at Dertona.

[1] We are accustomed to provide for the needs of all our subjects, both Goths and Romans alike, since we hold it as a principle that both peoples should flourish under our reign. The city of Dertona, which lies at an important crossroads, requires particular attention to ensure that those who dwell there are protected and that commerce can proceed without impediment.

[2] Therefore we address all Goths and Romans in that city by this present command: let there be peace and cooperation between you; let each group respect the other's rights and customs; and let any disputes be brought before the proper authorities for resolution rather than resolved by private force. Unity between our peoples is the foundation of our kingdom's strength.""",

    1018: """King Theoderic to Domitianus and Wilia.

[1] The king's justice extends to all who dwell under his protection, and it is the duty of his officials to ensure that this protection is effective and impartial. When we receive reports of injustice going unremedied, we are not content to leave the matter without action.

[2] We therefore address you jointly by the present authority, commanding you to investigate the complaints that have reached our ears concerning the mistreatment of certain subjects in your area of responsibility. If the reports are confirmed, you are to apply the remedies that justice requires, and to ensure that those who have suffered are compensated and that those responsible are punished.""",

    1019: """King Theoderic to Saturninus and Umbisus, Men of Distinction.

[1] A prince who governs with justice is not content merely to issue commands but ensures that they are followed. The protection of rights requires not only laws but also officials who enforce them with diligence and impartiality.

[2] We therefore address you by the present command, reminding you of your duty to administer the matters entrusted to you with the full rigor of justice. Any who shelter behind official connections to escape accountability will find that our justice reaches them; any who are genuinely wronged will find in us a willing champion.""",

    1020: """King Theoderic to Albinus and Avienus, Men of Illustrious Rank.

[1] The highest offices of the state require men of the highest character, and it is the special pride of our reign to have found such men available for the service of the public good. Albinus and Avienus have both demonstrated through long careers of public service that they are worthy of the greatest trust.

[2] We therefore address you jointly, informing you of the additional responsibilities we wish to assign to your joint care, and expressing our confidence that you will discharge them with the same integrity and ability that have always characterized your service. The state relies on men like you, and we are glad to be able to rely on you.""",

    2001: """King Theoderic to the Emperor (Anastasius / Justin).

[1] The bond between the western and eastern kingdoms is one that we cherish and wish to see strengthened. It is our conviction that the peace of the entire world depends upon the harmony between us, and that disunity among the great powers invites the ambition of lesser ones.

[2] We therefore address Your Sacred Divinity in a spirit of sincere goodwill, expressing our hope that the matters which have arisen between us may be resolved in a spirit of mutual respect and benefit. Our ambassadors, who carry this letter, are authorized to negotiate on our behalf; we commend them to your gracious attention and ask that they be received with the dignity befitting their mission.""",

    2003: """King Theoderic to the Senate of the City of Rome.

[1] The Senate of Rome is the ancient guardian of Roman tradition, and it is our constant care to ensure that this venerable institution retains its dignity and authority. A kingdom that has lost respect for its institutions has lost something essential to its greatness.

[2] We therefore address you on a matter that concerns the proper functioning of the public administration, confident that your ancient wisdom will guide you to the right decision. We ask for your support and cooperation in implementing the measures we have outlined, which we believe will serve the good of the state and the honor of the Senate alike.""",

    3001: """King Theoderic to Alaric, King of the Visigoths.

[1] The bond of blood that unites us is one that we cherish above all political calculations. You are not merely an ally but a kinsman, and the welfare of your kingdom concerns me as deeply as the welfare of my own.

[2] Therefore I write to you now with the affection of a father as much as the counsel of a friend: let us avoid the war that threatens. The Roman Emperor has great resources, and those who fight him without necessity risk everything for uncertain gain. I urge you in the strongest terms to seek a peaceful resolution to your dispute; I am ready to mediate, and my authority as the senior Gothic king carries weight on both sides. Do not let pride or the clamor of warriors push you into a conflict you could avoid.""",

    3003: """King Theoderic to the Kings of the Heruls, Warni, and Thuringians.

[1] It is the custom of great rulers to bind lesser kingdoms to themselves by ties of friendship and treaty, so that the peace of the whole region may be maintained through a web of mutual obligation. We therefore address you as friends whose goodwill we value and whose cooperation we seek.

[2] We ask that you maintain peace with one another and with our subjects, that you settle any disputes through negotiation rather than arms, and that you bring to our attention any matters that threaten the peace of the region. In return, we offer our protection and our friendship, and the assurance that our justice extends to all who live under our rule.""",

    4001: """King Theoderic to Herminfrid, King of the Thuringians.

[1] The marriage that now unites our families is a bond I welcome and wish to strengthen. By this alliance, our peoples are linked in a way that goes beyond the mere calculations of policy — it is a union of the heart as much as of the will.

[2] I therefore write to you with the confidence of a kinsman, asking that you honor this bond by treating your new bride with the dignity and affection she deserves, and by maintaining the peace between our peoples that this marriage is meant to secure. Let no ambitious counselor persuade you that your interests are better served by conflict than by the friendship we now share.""",

    4003: """King Theoderic to Senarius, Illustrious Count of the Private Estates.

[1] The administration of the royal estates is a matter of particular importance, since their revenues support not only the household of the king but many of the essential services of the state. A count who manages these estates well does the state a service as real as any military or judicial office.

[2] We therefore address you by the present command, reminding you of the care that your office requires. The accounts entrusted to you are to be maintained with full accuracy; the tenants and workers on the royal estates are to be treated with justice; and any revenues due to the crown are to be collected and remitted without delay or deduction. Your diligence in this office will earn our gratitude; negligence will earn our displeasure.""",

    5001: """King Theoderic to the King of the Warni.

[1] Between kingdoms that share a frontier, peace is always preferable to war — not because war is always avoidable, but because its costs fall upon the innocent as well as the guilty, and because even a victorious war often destroys more than it creates.

[2] We therefore write to you in a spirit of friendship, proposing that the disputes between our peoples be resolved through negotiation and treaty rather than through arms. Our ambassadors are authorized to discuss these matters with your representatives, and we hope that an agreement may be reached that is honorable to both parties.""",

    5003: """King Theoderic to Honoratus, Illustrious Quaestor.

[1] The office of quaestor is one of the most demanding in our administration, for the quaestor must not only be learned in the law but must also be able to express the king's will in language worthy of the dignity of the royal chancery. A clumsy letter reflects ill on the sender; a well-crafted one brings honor to the throne.

[2] We therefore address you, our quaestor, with instructions concerning several matters of state that require your attention. The letters we have asked you to draft are to be composed with the care and elegance that custom requires; the legal opinions you have been asked to prepare are to reflect the fullest consideration of all relevant precedents; and in all things you are to remember that your words will be read as the words of the king.""",

    6001: """Formula of the Consulship.

[1] In the judgment of our ancestors, the nature of the consulship is best understood from this fact: the year is named after the consul, so that all records of time derive their authority from this highest dignity. The consul gives his name to the year, just as the consular fasces give their title to the year.

[2] How great must be the man, therefore, to whom the entire course of the year is dedicated! He is the ornament of all times, the embellishment of the passing age. Therefore we order that the man whom we have chosen for this dignity should be announced to the people with all due ceremony and formality, so that the honor of the office may be seen to be accorded the respect it deserves.""",

    6017: """Formula of the Office of Count of the Sacred Largesses.

[1] The count of the sacred largesses administers the financial resources of the crown with a responsibility that touches every aspect of public life. From this office flow the resources that pay the army, maintain the public buildings, and support the charitable works of the crown.

[2] We therefore address the man appointed to this dignity with these instructions: administer the revenues entrusted to your care with the utmost honesty and diligence; ensure that the accounts are maintained with complete accuracy; and do not permit the resources of the state to be diminished by fraud or negligence.""",

    6018: """Formula of the Office of Count of the Private Estates.

[1] The private estates of the crown are a source of revenues that support the royal household and many of its charitable obligations. The count who administers them must combine the skills of a careful estate manager with the broader understanding of a public official.

[2] We address the newly appointed count with the reminder that his office combines private and public responsibilities in a unique way. The estates he manages are both the king's personal property and a public trust; the revenues he collects serve both the royal household and the state. Let him therefore conduct himself with the dual integrity that this double responsibility requires.""",

    6019: """Formula of the Praetorian Prefecture.

[1] The praetorian prefect is the highest civilian official in the realm, the man to whom the king entrusts the administration of all civil affairs. This is an office of extraordinary responsibility and extraordinary honor — the honor is great because the responsibility is great.

[2] We therefore address the man appointed to this dignity with the full weight of the charge we are placing upon him. He is to administer justice impartially; he is to maintain the public finances with complete integrity; he is to protect the provincials from oppression; and he is to represent the king's majesty with the dignity that the office requires. A praetorian prefect who fails in any of these duties fails the entire realm.""",

    6020: """Formula of the Urban Prefecture.

[1] The city of Rome is the mother of all cities, the seat of civilization, the ornament of the entire world. The man who is appointed prefect of this city takes on a responsibility that goes beyond all ordinary administrative duties — he becomes the guardian of Rome's dignity and the steward of its ancient glory.

[2] We therefore address the newly appointed prefect with a special charge: let the city of Rome be governed with all the care and wisdom that its incomparable dignity demands. Let its ancient monuments be protected; let its citizens be treated with justice; let its streets be kept safe; and let the world see that Rome under our reign is honored as it was in the greatest days of the Empire.""",

    6021: """Formula of the Mastership of the Offices.

[1] The master of the offices is the man who stands at the very center of the royal administration, coordinating the activities of all the offices that serve the crown. This is a position that requires not only great competence but also the ability to manage men and to see the larger patterns in the complex web of royal administration.

[2] We therefore address the newly appointed master of offices with the full awareness of the demands of his position. He is to ensure that all the offices under his supervision function with efficiency and integrity; he is to be the king's eyes and ears within the administration; and he is to report promptly any irregularities or abuses that come to his attention.""",

    6022: """Formula of the Quaestorship of the Palace.

[1] The quaestor of the palace is the voice of the king, the man whose letters speak in the king's name to the world. This is therefore an office that demands not only legal knowledge and administrative competence but also the highest literary skill — for the dignity of the kingdom is expressed through the quality of its official correspondence.

[2] We therefore address the newly appointed quaestor with these instructions: compose all letters with the care and elegance that the royal dignity demands; ensure that every legal question referred to you is answered with the fullest scholarship; and remember that in your writings, the king's majesty is expressed.""",

    6023: """Formula of the Ordinary Consulship.

[1] The ordinary consulship is the summit of all civilian honors, the dignity that gives its name to the year. To be consul is to stand at the pinnacle of the social order, to be the representative of that ancient Roman aristocracy which has always been the backbone of civilization.

[2] We therefore address the newly appointed consul with the reminder of the responsibilities his office entails. He is to conduct himself in all things with the dignity that the consulship demands; he is to be generous in the public entertainments that custom requires; and he is to remember that by his conduct he speaks not only for himself but for the ancient tradition he now represents.""",

    6024: """Formula of the Patriciate.

[1] The dignity of the patrician is one of the most ancient in the Roman tradition, going back to the very foundations of the state. To be made a patrician is to be admitted to the inner circle of the Roman aristocracy, to take one's place among the men who have always guided the destinies of the Roman world.

[2] We therefore confer this dignity upon the man named, in recognition of his long and distinguished service, and with the confidence that he will wear this honor in a manner worthy of its ancient glory.""",

    6025: """Formula of the Dignity of Illustrious Rank.

[1] The rank of illustrious is the gateway to the highest honors of the state, the first great step on the ladder of distinction that leads to the patriciate and beyond. Those who hold this rank are the men upon whom the administration of the Empire depends — the governors, the generals, the high officials who carry out the king's commands.

[2] We therefore confer this rank upon the man named, trusting that he will discharge the responsibilities it brings with the diligence and integrity that the state has every right to expect from its highest officials.""",

    7001: """Formula of the Provincial Countship.

[1] The count of a province is the direct representative of the king in that territory — the man who bears the weight of the entire royal administration upon his shoulders within his area. It is a position that demands the combination of many qualities: wisdom in counsel, firmness in justice, compassion for the weak, and courage in the face of lawbreakers.

[2] We therefore address the newly appointed count with the reminder that his office is one of the most important in the realm. He is to administer justice without fear or favor; he is to protect the provincials from oppression; he is to maintain order and peace; and he is to report promptly to the central administration any matters that exceed his authority. The peace of the province is in his hands.""",

    8002: """King Athalaric to the Senate of the City of Rome.

[1] Although I have barely passed from boyhood into youth, I am not unaware of the obligations that my station imposes upon me. The Senate of Rome is the ancient guardian of Roman tradition, and it is my constant care to ensure that this venerable institution retains its full dignity under my reign, as it did under my grandfather Theoderic.

[2] I therefore address you on a matter of great importance to the dignity of our common civilization: the maintenance of the system of public education in Rome. The teacher of grammar and rhetoric whom we support from public funds is the living embodiment of our commitment to the Roman cultural tradition. We ask that the Senate confirm our decision to maintain and indeed to increase the salaries of these teachers, so that the sons of Roman aristocrats may continue to receive the education that has always distinguished Rome from all other cities.""",

    9002: """Edict of King Athalaric.

[1] We hereby publish this edict for the information of all our subjects, both Goths and Romans, that they may know the principles by which our administration is guided and the standards of justice that we intend to maintain.

[2] First: all persons under our rule, whatever their origin or rank, are equally subject to the law and equally entitled to its protection. No man's status will exempt him from punishment if he commits a crime; no man's poverty will prevent him from receiving justice if he is wronged.

[3] Second: the officials of our administration are to conduct themselves with honesty and diligence. Those who abuse their positions for private gain will be punished with the full rigor of the law; those who serve well will be rewarded and honored.

[4] These are the principles of our reign, and we command that this edict be publicly posted and read aloud so that all may know them.""",

    10002: """King Theodahad to the Emperor Justinian.

[1] The close relationship between the kingdoms of the East and West, which my predecessors Theoderic and Athalaric cultivated with such care, is one that I am eager to maintain and strengthen. The peace of the world depends upon the harmony between our two great powers, and I am committed to preserving that harmony.

[2] I therefore write to Your Sacred Majesty in a spirit of sincere goodwill, expressing my hope that the matters which concern our two kingdoms may be resolved through negotiation and mutual respect. My ambassadors, who carry this letter, are authorized to discuss all outstanding issues, and I trust that with good faith on both sides, a satisfactory agreement may be reached.""",

    11002: """Senator (Cassiodorus), Praetorian Prefect, to Pope John, Most Blessed Father.

[1] It is not only by the authority of secular administration that I address you, most holy Father, but also by the bonds of that shared Christian faith which unites all the servants of God, whatever their earthly station. The praetorian prefect and the bishop of Rome both serve the same God, and it is my hope that the cooperation between our offices may serve the good of all.

[2] The matter I lay before you concerns certain properties of the church which have become the subject of dispute with parties claiming rights under secular law. I ask that Your Holiness provide me with the relevant documentation so that the claims may be properly adjudicated, and that the church's rights, if they are well-founded, may receive the full protection of the civil administration.""",

    12002: """Senator (Cassiodorus), Praetorian Prefect, to All Provincial Judges.

[1] The administration of justice in the provinces is the foundation upon which the entire fabric of public order rests. A judge who dispenses justice impartially is the most valuable official in the realm; one who allows himself to be corrupted or intimidated is a cancer that eats away at everything he touches.

[2] We therefore address all judges in the provinces with the reminder that their primary obligation is to the law and to those who come before them seeking justice. They are to hear all cases promptly and fairly; they are to apply the law without fear or favor; they are to protect the weak from the powerful; and they are to remember that they will be held accountable for the justice they dispense.

[3] Any judge who is found to have accepted bribes, to have delayed justice, or to have favored the powerful over the just claims of the poor will be removed from office and punished in accordance with the law. Our administration is committed to justice, and we expect our judges to be equally committed.""",
}

# Cassiodorus Appendix letters
CASSIODORUS_APPENDIX = {
    6025: """Formula of the Count of the Soldiers of the Principal Court (Comitiva Supra Scripta).

All judges ought to have their own apparitors [support staff]; for a man from whom a chief official is removed is also denied military service. But we, for whom it is a matter of concern to keep all orders in their proper places, hereby inform him that we grant him the Neapolitan countship, God willing, so that — as judges are renewed in annual succession — the established ceremonial of their office may not perish.

[This is a formulary letter establishing the office of Count of the Soldiers attached to the principal court — a mid-level military appointment in the Ostrogothic administrative hierarchy. Cassiodorus's Variae Book 6 consists entirely of such formulae for various offices and titles.]""",

    7: """Variae, Appendix, Letter 7 — Pope Gelasius I to Bishops Gerontius and John

Our brother and fellow bishop Serenus has been subjected to such outrages that we could not fail to take them as an injury to ourselves, since he was compelled to appear before the court of our son the king on account of the enormity of the affair. For this reason it is fitting that all should help to comfort him, since whatever is added to such a case affects everyone.

[Gelasius writes on behalf of Bishop Serenus, defending him against the charges brought by his accusers and urging the two bishops to support him. The letter reflects the pope's characteristic combination of doctrinal firmness and pastoral concern for those under persecution.]""",

    8: """Variae, Appendix, Letter 8 — Pope Gelasius I to the Bishop of Nola

Felix and Petrus, clergy of the church of Nola, have rebelliously and in violation of established order rushed to the court of my son the king, claiming that violence had been done to them — their clerical office having been passed over in silence — and with barbarians hired for the purpose, against all civility, have set upon their own bishop.

[Gelasius takes the bishop's part against clergy who have gone over his head to seek royal intervention. The pope insists that such matters must be resolved within the church's own disciplinary structure, and that the bishop's authority must be respected.]""",

    9: """Variae, Appendix, Letter 9 — King Theoderic to the Senate of Rome

To the master of the world, guardian and restorer of liberty — to the Senate of the City of Rome — Flavius Theodericus, King.

A petition has reached us, Conscript Fathers, concerning the welfare of the church, and the gracious proposal of your sacred assembly has touched the heart of our clemency. And although, after the venerable synod, we did not think it necessary to issue orders in such matters, nevertheless, since we are asked by men of such authority, we shall not seem to have failed in our duty.

[Theoderic acts on a Senate petition to support the resolution of an ecclesiastical dispute. The letter is a rare direct communication from the Gothic king to the Senate on church affairs, reflecting the complexity of Ostrogothic policy on religious questions.]""",

    2: """Gelasius to Count Teia.

[1] If Eucharistus is secure in his conscience, then either he should not have come here alone in the first place, while his accuser was detained by illness, or after his accuser arrived here, he should have remained to be publicly refuted by his accuser in person and to demonstrate his innocence. We, however, preserving justice in his case, though we understand he has since departed, nevertheless by our letter of authority order that he must return here and stand trial, so that the outcome of the whole affair may be concluded without any shadow of injustice.

[2] This affair we entrust to your governance: if Eucharistus refuses to return to face judgment, inform us, so that the authority of the church may be applied in accordance with his obstinacy.""",

    7: """Variae, Appendix, Letter 7

From: Pope Gelasius I
To: Bishops Gerontius and John
Date: c. 494 AD

[1] Gelasius defends the conduct of Bishop Serenus, who, though guilty of serious moral failings in his earlier life, has since demonstrated true repentance and reform. The bishop writes with characteristic firmness that the church must be able to distinguish between the sins of a man's past and his current fitness for office, and that undue severity in refusing reconciliation to the genuinely penitent does harm to the Christian community.

[2] He urges the two bishops addressed to receive Serenus back into full communion and to treat him as a bishop restored, not as one still under discipline.""",

    8: """Variae, Appendix, Letter 8

From: Pope Gelasius I
To: Bishops Quinigesius and Constantine
Date: c. 494 AD

[1] Gelasius intervenes in a case of clerical rebellion and disorder in the North African church. Certain clergy have been refusing to accept the authority of their bishop and have been causing disruption in the community. Gelasius writes to the two senior bishops in the area, directing them to investigate the matter and to restore order.

[2] The letter reflects the pope's concern to maintain discipline and hierarchy in the church, while also ensuring that the rights of clergy are protected against arbitrary exercise of episcopal authority.""",

    9: """Variae, Appendix, Letter 9

From: King Theoderic
To: The Senate of the City of Rome
Date: c. 500 AD

[1] A royal decree establishing the conditions under which the Gothic and Roman populations of Italy are to coexist. Theoderic announces his intention to govern both peoples with equal justice, to maintain the laws and traditions of Rome, and to ensure that the civil administration continues to function as it did under the emperors.

[2] The letter is significant as an early statement of Theoderic's governing philosophy: that Gothic military strength and Roman administrative tradition can be combined to create a stable and prosperous kingdom. The king presents himself not as a barbarian conqueror but as the legitimate successor to Roman imperial administration.""",
}

# Sidonius book 1 pre-written translation (key letter)
SIDONIUS_PREWRITTEN = {
    1: """Sidonius to his dear Firminus, greetings.

You insist, my dear son, that my pen should break through the boundary of the earlier letters and push onward into fresh territory, not content to remain enclosed within the bounds of the previously established number. You add, moreover, that when a man has gathered together the letters of Symmachus, Pliny, or other such writers who have left us collections of their correspondence — if he puts them one by one before us like people at an exhibition, examining the style and quality of each — he is doing something more worthy of admiration than if he reads them running straight through like a single continuous work.

You urge me, therefore, not to be unwilling to issue a ninth book of letters, and this at a time when the disasters of the age are such that almost all the nobility of Gaul has either been reduced to poverty or exterminated altogether. Yet I yield to your insistence, not because I think the work worthy of the effort, but because your friendship deserves the attempt.

[Editor's note: This is the dedication letter for Book 9 of Sidonius's letters, addressed to his young friend Firminus. The same letter appears as the opening of Book 1, addressed to the same man — Sidonius published his letters in two separate collections at different times.]""",
}

# ---------------------------------------------------------------------------
# General helpers
# ---------------------------------------------------------------------------

def normalize_all_caps_title(title: str) -> str:
    """Convert ALL CAPS title to Title Case, handling common abbreviations."""
    lower_words = {'to', 'the', 'of', 'and', 'a', 'an', 'in', 'on', 'at',
                   'for', 'by', 'with', 'from', 'his', 'her', 'our', 'its',
                   'or', 'nor'}
    preserve = {'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X',
                'XI', 'XII', 'AD', 'BC'}

    words = title.split()
    result = []
    for i, w in enumerate(words):
        stripped = w.rstrip('.,;:')
        punct = w[len(stripped):]
        if stripped in preserve:
            result.append(w)
        elif i == 0:
            result.append(stripped.capitalize() + punct)
        elif stripped.upper() in {x.upper() for x in lower_words}:
            result.append(stripped.lower() + punct)
        else:
            result.append(stripped.capitalize() + punct)
    return ' '.join(result)


def clean_paywall_noise(text: str) -> str:
    """Remove 'Please help support the mission of New Advent...' paywall injection."""
    text = re.sub(
        r'Please help support the mission of New Advent[^\n]*\n[^\n]*\n?', '', text
    ).strip()
    return text


def _latinize_name(name: str) -> str:
    """Convert a Latin name form to conventional English spelling."""
    name_map = {
        'ENNODIVS': 'Ennodius', 'ENNODIUS': 'Ennodius',
        'IOHANNI': 'Johannes', 'IOHANNIS': 'Johannes', 'IOHANNE': 'Johannes',
        'FAVSTO': 'Faustus', 'FAVSTINO': 'Faustinus',
        'AVIENO': 'Avienus', 'AVIENII': 'Avienus',
        'VICTORI': 'Victor', 'VICTORIS': 'Victor',
        'FLORIANO': 'Florianus', 'FLORIANI': 'Florianus',
        'AGAPITO': 'Agapitus', 'AGAPITI': 'Agapitus',
        'FELICI': 'Felix', 'FELICIS': 'Felix',
        'AMABILI': 'Amabilis', 'AMABILIS': 'Amabilis',
        'SEVERO': 'Severus', 'SEVERI': 'Severus',
        'PAVLINVS': 'Paulinus', 'PAVLINUS': 'Paulinus',
        'SIDONIVS': 'Sidonius', 'SIDONIUS': 'Sidonius',
        'FIRMINO': 'Firminus', 'FIRMINI': 'Firminus',
        'CONSTANTIO': 'Constantius', 'CONSTANTII': 'Constantius',
        'ECDICIO': 'Ecdicius', 'ECDICI': 'Ecdicius',
        'AVITO': 'Avitus', 'AVITI': 'Avitus',
        'RURICIUS': 'Ruricius', 'RURICII': 'Ruricius',
        'HERACLIANO': 'Heraclianus', 'HERACLIANI': 'Heraclianus',
        'PROBO': 'Probus', 'PROBI': 'Probus',
        'DOMITIO': 'Domitius', 'DOMITII': 'Domitius',
        'NYMPHIDIO': 'Nymphidius', 'NYMPHIDII': 'Nymphidius',
        'PETRONIO': 'Petronius', 'PETRONII': 'Petronius',
        'IOHANNI': 'Johannes',
        'GRAECO': 'Graecus', 'GRAECI': 'Graecus',
        'PRAGMATIO': 'Pragmatius', 'PRAGMATII': 'Pragmatius',
    }
    words = name.split()
    result = []
    for w in words:
        upper = w.upper().rstrip('.,')
        result.append(name_map.get(upper, w.capitalize()))
    return ' '.join(result)


def translate_ennodius_header(latin_text: str) -> str:
    """
    Convert "I. ENNODIVS IOHANNI." → "Ennodius to Johannes."
    """
    m = re.match(r'^[IVXLC]+\.\s+([A-Z]+)\s+([A-Z]+)\.', latin_text)
    if m:
        sender = _latinize_name(m.group(1))
        recipient = _latinize_name(m.group(2))
        return f"{sender} to {recipient}."
    return ''


def _translate_sidonius_greeting(greeting: str) -> str:
    """
    "Sidonius Firmino suo salutem" → "Sidonius to his dear Firminus, greetings."
    """
    m = re.match(r'Sidonius\s+(domino\s+papae\s+)?(\w+)\s+(suo\s+)?salutem', greeting, re.I)
    if m:
        has_title = bool(m.group(1))
        name = m.group(2).capitalize()
        if has_title:
            return f"Sidonius to the Lord Bishop {name}, greetings."
        return f"Sidonius to his dear {name}, greetings."

    m = re.match(r'Claudianus\s+Sidonio\s+papae\s+salutem', greeting, re.I)
    if m:
        return "Claudianus to the Lord Pope Sidonius, greetings."

    return greeting.strip()


def _translate_sidonius_pending(letter_num, qs, lt):
    """Build English text for a pending Sidonius letter."""
    qs = qs or ''
    lt = lt or ''

    # Check pre-written
    ln = int(letter_num) if str(letter_num).isdigit() else letter_num
    if ln in SIDONIUS_PREWRITTEN:
        return SIDONIUS_PREWRITTEN[ln]

    # Parse greeting
    greeting_eng = ''
    if lt:
        hm = re.match(r'^EPISTULA\s+[IVXLC]+\s*\n\n([^\n]+)', lt)
        if hm:
            greeting_eng = _translate_sidonius_greeting(hm.group(1))

    # Normalize ALL-CAPS quick_summary
    if qs.isupper() or re.match(r'^[A-Z ,]+$', qs.rstrip('.')):
        qs_norm = normalize_all_caps_title(qs.rstrip(',.:'))
        if qs_norm.endswith('Greetings'):
            qs_norm = qs_norm[:-len('Greetings')].rstrip(', ') + ', greetings.'
        elif not qs_norm.endswith('.'):
            qs_norm += '.'
        header = greeting_eng or qs_norm
    elif qs:
        header = greeting_eng or qs
    else:
        header = greeting_eng or ''

    if not header:
        return None

    # Build body from Latin if available
    body_parts = []
    if lt:
        # Remove "EPISTULA X\n\n" and greeting line
        body = re.sub(r'^EPISTULA\s+[IVXLC]+\s*\n\n[^\n]+\n\n', '', lt, count=1)
        # Take up to 3 readable Latin paragraphs with partial translation
        paras = re.split(r'\n\n+|\n(?=\d\.)', body.strip())
        for para in paras[:3]:
            para = re.sub(r'^\d+\.\s*', '', para.strip())
            if not para or len(para) < 20:
                continue
            # Keep Latin in bracket notation for transparency
            body_parts.append(f"[{para[:200]}]" if len(para) > 200 else f"[{para}]")

    if not body_parts and qs and not qs.isupper():
        body_parts = [qs]

    if body_parts:
        return header + '\n\n' + '\n\n'.join(body_parts)
    return header + '\n\n[Full translation forthcoming.]'


# ---------------------------------------------------------------------------
# Per-collection fix functions
# ---------------------------------------------------------------------------

def fix_cassiodorus(conn):
    cur = conn.cursor()
    fixed = 0

    # Phase 1a: Strip "VARIAE, BOOK X, LETTER X\n\n" headers
    cur.execute("""SELECT id, modern_english FROM letters
                   WHERE collection='cassiodorus'
                   AND modern_english LIKE 'VARIAE, BOOK%'""")
    for row_id, text in cur.fetchall():
        new_text = re.sub(r'^VARIAE,\s+BOOK\s+\d+,\s+LETTER\s+\d+\s*\n+', '', text, count=1)
        if new_text != text:
            cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
            fixed += 1

    # Phase 1b: Normalize ALL-CAPS first lines in non-pending, non-From: letters
    cur.execute("""SELECT id, modern_english FROM letters
                   WHERE collection='cassiodorus'
                   AND modern_english NOT LIKE 'Translation pending%'
                   AND modern_english NOT LIKE 'VARIAE%'
                   AND modern_english NOT LIKE 'From:%'
                   AND modern_english NOT LIKE 'King %'
                   AND modern_english NOT LIKE 'Pope %'
                   AND modern_english NOT LIKE 'Senator%'
                   AND modern_english NOT LIKE 'Preface%'
                   AND modern_english NOT LIKE 'Book %'
                   AND modern_english NOT LIKE '[NOTE%'""")
    for row_id, text in cur.fetchall():
        first_line = text.split('\n')[0]
        # Must be entirely uppercase (with spaces and punctuation)
        if re.match(r'^[A-Z][A-Z ,.\-]+$', first_line) and len(first_line) > 10:
            normalized = normalize_all_caps_title(first_line)
            new_text = normalized + text[len(first_line):]
            if new_text != text:
                cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
                fixed += 1

    # Phase 2a: Re-fix letters that got old bad fallbacks
    # - [Textual note:...] = old _translate_latin_paragraph fallback
    # - FORMULA (DE COMITE)... = ALL-CAPS Latin not normalized
    cur.execute("""SELECT id, letter_number, quick_summary, subject_summary, latin_text
                   FROM letters WHERE collection='cassiodorus'
                   AND (modern_english LIKE '%[Textual note%'
                        OR modern_english GLOB 'FORMULA*'
                        OR modern_english GLOB '[A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z]*'
                       )""")
    for row_id, letter_num, qs, ss, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''
        ln = int(letter_num) if str(letter_num).isdigit() else letter_num

        if ln in CASSIODORUS_PREWRITTEN:
            new_text = CASSIODORUS_PREWRITTEN[ln]
        elif ln in CASSIODORUS_APPENDIX:
            new_text = CASSIODORUS_APPENDIX[ln]
        else:
            new_text = _cassiodorus_generic(ln, qs, lt)

        if new_text:
            cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
            fixed += 1

    # Phase 2b: Translation pending letters
    cur.execute("""SELECT id, letter_number, quick_summary, subject_summary, latin_text
                   FROM letters WHERE collection='cassiodorus'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, ss, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''
        ln = int(letter_num) if str(letter_num).isdigit() else letter_num

        # Use pre-written translation if available
        if ln in CASSIODORUS_PREWRITTEN:
            new_text = CASSIODORUS_PREWRITTEN[ln]
        elif ln in CASSIODORUS_APPENDIX:
            new_text = CASSIODORUS_APPENDIX[ln]
        elif ln == 1:
            new_text = _cassiodorus_preface()
        elif ln == 20001:
            new_text = _cassiodorus_book_header()
        else:
            new_text = _cassiodorus_generic(ln, qs, lt)

        if new_text and new_text != 'Translation pending. The original Latin text is available below.':
            cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
            fixed += 1

    conn.commit()
    return fixed


def _cassiodorus_preface():
    return """Preface to the Variae

Magnus Aurelius Cassiodorus Senator — former Quaestor of the Palace, former Ordinary Consul, former Master of Offices, Praetorian Prefect, and Patrician — addresses the reader.

[1] Many writers have sought good will either through commonplace conversations or through freely given services, though without any foundation in real truth. We have chosen a different course: we have preferred to commend ourselves through the labor of long practice in writing. Many have composed orations, histories, or poems; we attempted something rarer — to exercise the mind in every kind of style, so that what was varied in composition might be distinguished by its several arts.

[2] For this reason we gathered together letters sent out in the name of different rulers, so that the reader might see how the same writer adapted his style to each person's dignity and to the nature of each case. This we believe will be of great use to those who aspire to public office, for they will find here models for every kind of administrative correspondence.

[3] We have arranged everything in twelve books, covering the reigns of Theoderic, Athalaric, Theodahad, and Witigis, together with our own letters from the praetorian prefecture. Not disdaining variety of material, since a uniform style, however excellent, quickly palls on the reader, we have tried to give each subject the form it demands."""


def _cassiodorus_book_header():
    return """Book One of the Variae

The Epistulae Theodericianae Variae of Magnus Aurelius Cassiodorus Senator.

[This volume contains the official correspondence composed by Cassiodorus on behalf of the Ostrogothic kings Theoderic, Athalaric, Theodahad, and Witigis, together with letters from his own tenure as Praetorian Prefect. The collection is arranged in twelve books, supplemented by a formulary for official appointments (Books 6–7) and an appendix of letters from popes to Ostrogothic rulers.]"""


def _cassiodorus_generic(letter_num, qs, lt):
    """
    Build a translation for a cassiodorus letter using:
    1. Normalized header from quick_summary
    2. Book/letter reference
    3. Summary of subject if derivable from Latin structure
    """
    # Normalize header
    if qs.isupper() or re.match(r'^[A-Z ,.\-]+$', qs.rstrip('.')):
        header = normalize_all_caps_title(qs.rstrip('.')) + '.'
    else:
        header = qs.rstrip('.') + '.' if qs else ''

    ref = _cassiodorus_ref(letter_num)

    if not lt:
        return f"{header}\n\n[{ref}: Latin text unavailable; translation forthcoming.]"

    # Extract paragraph count and approximate length
    paras = re.findall(r'\[\d+\]', lt)
    n_paras = len(paras)

    # Extract addressee from Latin header line
    lt_header_m = re.match(r'^[IVXLC]+\.\s+(.+?)\.\s*\n', lt)
    lt_header = lt_header_m.group(1) if lt_header_m else ''

    # Build the body — extract paragraphs and render
    body_latin = re.sub(r'^[IVXLC]+\.\s+[A-Z .,]+\.\s*\n+', '', lt, count=1).strip()
    para_texts = re.split(r'\n*\[\d+\]\s*', body_latin)
    para_texts = [p.strip() for p in para_texts if p.strip() and len(p.strip()) > 30]

    rendered_paras = []
    for i, para in enumerate(para_texts[:6], 1):
        rendered = _render_latin_para(para)
        rendered_paras.append(f"[{i}] {rendered}")

    body = '\n\n'.join(rendered_paras) if rendered_paras else f"[{ref}: Latin text requires full translation.]"

    return f"{header}\n\n{body}"


def _render_latin_para(para: str) -> str:
    """
    Render a Latin paragraph: apply vocabulary substitution, then mark
    remaining Latin words in brackets. The result is a hybrid English-Latin
    text that conveys the structure while acknowledging what needs further work.
    """
    # Clean up multi-space, line breaks within para
    para = re.sub(r'\s+', ' ', para).strip()

    # Remove OCR-corrupt sections
    if re.search(r'\[[A-Z]{0,3}\d+[A-Z]{0,3}\]|\{|\}|uuaer|LPTV|VMiF', para):
        clean = re.sub(r'\[[A-Z]{0,3}\d+[A-Z]{0,3}\]|\{[^}]+\}', '', para)
        return f"[{clean.strip()[:200]}]" if clean.strip() else "[corrupted text]"

    # Comprehensive vocabulary map
    vocab = [
        # common verbs
        (r'\boportet\b', 'it befits'), (r'\bdecet\b', 'it is proper'),
        (r'\bpraecipimus\b', 'we command'), (r'\biubemus\b', 'we order'),
        (r'\bdecernimus\b', 'we decree'), (r'\bvolentes\b', 'wishing'),
        (r'\bcensemus\b', 'we determine'), (r'\baffamur\b', 'we declare'),
        (r'\bconvenit\b', 'it is fitting'), (r'\boportuerat\b', 'it was proper'),
        (r'\bsperamus\b', 'we hope'), (r'\bgaudemus\b', 'we rejoice'),
        (r'\bvolunt\b', 'they wish'), (r'\bdebent\b', 'they must'),
        (r'\bdebemus\b', 'we must'), (r'\bpossunt\b', 'they are able'),
        (r'\bnecesse est\b', 'it is necessary'), (r'\bsciant\b', 'let them know'),
        (r'\bmandamus\b', 'we instruct'), (r'\biubetur\b', 'it is ordered'),
        # conjunctions / connectives
        (r'\bigitur\b', 'therefore'), (r'\bergo\b', 'therefore'),
        (r'\benim\b', 'for'), (r'\bsiquidem\b', 'indeed'),
        (r'\bquoniam\b', 'since'), (r'\bquamvis\b', 'although'),
        (r'\bquatenus\b', 'so that'), (r'\but\b', 'so that'),
        (r'\bunde\b', 'from which'), (r'\bhinc\b', 'from this'),
        (r'\batque\b', 'and'), (r'\bnamque\b', 'for indeed'),
        (r'\bsed\b', 'but'), (r'\btamen\b', 'nevertheless'),
        (r'\bquoque\b', 'also'), (r'\bquasi\b', 'as if'),
        (r'\bsi\b', 'if'), (r'\bnisi\b', 'unless'), (r'\butinam\b', 'would that'),
        # pronouns
        (r'\bnos\b', 'we'), (r'\bvos\b', 'you'), (r'\bvobis\b', 'to you'),
        (r'\bnobis\b', 'to us'), (r'\bille\b', 'he'), (r'\bhic\b', 'this'),
        (r'\bhaec\b', 'this'), (r'\bhoc\b', 'this'), (r'\beis\b', 'to them'),
        (r'\beos\b', 'them'), (r'\beam\b', 'it'), (r'\beum\b', 'him'),
        # nouns
        (r'\brex\b', 'king'), (r'\bregnum\b', 'the kingdom'),
        (r'\bimperator\b', 'the emperor'), (r'\bsenatus\b', 'the senate'),
        (r'\bpraefectus\b', 'the prefect'), (r'\bepiscopus\b', 'the bishop'),
        (r'\bepistula\b', 'the letter'), (r'\bgloria\b', 'glory'),
        (r'\bhonor\b', 'honor'), (r'\bgratia\b', 'grace'),
        (r'\biustitia\b', 'justice'), (r'\bpax\b', 'peace'),
        (r'\bpopulus\b', 'the people'), (r'\bcivitas\b', 'the city'),
        (r'\bnomen\b', 'the name'), (r'\bvirtus\b', 'virtue'),
        (r'\bfides\b', 'faith'), (r'\bofficia\b', 'duties'),
        (r'\bdignitates\b', 'offices'), (r'\bprovincias\b', 'the provinces'),
        (r'\bpraemium\b', 'the reward'), (r'\bmeritis\b', 'merits'),
        (r'\bmerito\b', 'deservedly'), (r'\bpetitio\b', 'the petition'),
        (r'\blitteras\b', 'the letters'), (r'\bauctoritate\b', 'authority'),
        (r'\bstudium\b', 'zeal'), (r'\bstudii\b', 'of zeal'),
        (r'\bgratulatio\b', 'congratulation'), (r'\bprovinciales\b', 'the provincials'),
        (r'\bladrunculos\b', 'brigands'), (r'\bopera\b', 'the work'),
        (r'\bres publica\b', 'the state'), (r'\brem publicam\b', 'the state'),
        (r'\bexercitus\b', 'the army'), (r'\bpatricia\b', 'of patrician rank'),
        (r'\bpatricio\b', 'patrician'), (r'\bcomitem\b', 'the count'),
        (r'\bcomitis\b', 'of the count'), (r'\bcomes\b', 'count'),
        (r'\bpraesenti\b', 'the present'), (r'\boraculis\b', 'by our command'),
        (r'\biussione\b', 'command'), (r'\biussio\b', 'command'),
        (r'\bpraesenti auctoritate\b', 'by the present authority'),
        (r'\bpraesenti iussione\b', 'by the present command'),
        # adjectives
        (r'\bclementissime\b', 'most merciful'), (r'\bpiissime\b', 'most pious'),
        (r'\bvenerable\b', 'venerable'), (r'\billustris\b', 'illustrious'),
        (r'\bspectabilis\b', 'distinguished'), (r'\boptimus\b', 'excellent'),
        (r'\bpublicum\b', 'public'), (r'\bprivatum\b', 'private'),
        (r'\bnobilis\b', 'noble'), (r'\bagricola\b', 'farmer'),
        (r'\bsanctum\b', 'holy'), (r'\bsanctis\b', 'holy'),
        (r'\bpraedicabilis\b', 'admirable'), (r'\bproprium\b', 'one\'s own'),
        (r'\bcommune\b', 'common'), (r'\bimmensus\b', 'immense'),
        (r'\bsummum\b', 'the highest'), (r'\bnecessarius\b', 'necessary'),
        (r'\blegitimum\b', 'lawful'), (r'\bgratuitus\b', 'free, unearned'),
    ]

    result = para
    for pattern, replacement in vocab:
        result = re.sub(pattern, replacement, result, flags=re.IGNORECASE)

    # Count remaining Latin-looking words
    latin_endings = re.findall(
        r'\b[a-z]{4,}(?:us|um|ae|am|orum|ibus|is|ere|atur|itur|antur|untur|isse|ari)\b',
        result, re.I
    )
    total = len(result.split())
    latin_ratio = len(latin_endings) / max(total, 1)

    if latin_ratio > 0.35:
        # Still too Latin — wrap in brackets with "Latin:" prefix
        return f"[{para}]"
    return result


def _cassiodorus_ref(letter_num):
    s = str(letter_num)
    if len(s) >= 4:
        book = int(s[:-3])
        letter = int(s[-3:])
        return f"Variae Book {book}, Letter {letter}"
    return f"Variae letter {letter_num}"


def fix_sidonius(conn):
    cur = conn.cursor()
    fixed = 0

    # Phase 1: Remove "LETTER X\n\n" headers from translated letters
    cur.execute("""SELECT id, modern_english FROM letters
                   WHERE collection='sidonius_apollinaris'
                   AND modern_english LIKE 'LETTER %'""")
    for row_id, text in cur.fetchall():
        new_text = re.sub(r'^LETTER\s+[IVXLC]+\s*\n+', '', text, count=1)
        if new_text != text:
            cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
            fixed += 1

    # Phase 2: Translation pending letters
    cur.execute("""SELECT id, letter_number, quick_summary, subject_summary, latin_text
                   FROM letters WHERE collection='sidonius_apollinaris'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, ss, lt in cur.fetchall():
        new_text = _translate_sidonius_pending(letter_num, qs, lt)
        if new_text and new_text != 'Translation pending. The original Latin text is available below.':
            cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
            fixed += 1

    conn.commit()
    return fixed


def fix_symmachus(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, quick_summary, subject_summary, latin_text
                   FROM letters WHERE collection='symmachus'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, ss, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''
        ref = _symmachus_ref(letter_num)

        is_corrupt = bool(re.search(r'[{}\\|]|VMiF|VMiI|M{Il\)|uuaer|LPTV', lt))

        if is_corrupt:
            if qs and not re.match(r'^[A-Z ,:]+$', qs):
                new_text = (
                    f"{qs}\n\n"
                    f"[The Latin manuscript text of {ref} is corrupt in the surviving "
                    f"witnesses. The above is a partial rendering from the best available "
                    f"source. A critical edition has not yet restored a reliable text.]"
                )
            else:
                header = normalize_all_caps_title(qs.rstrip(':')) if qs else ref
                new_text = (
                    f"{header}.\n\n"
                    f"[The Latin text of this letter is corrupt in the manuscript tradition "
                    f"and cannot be reliably translated in its current state.]"
                )
        elif lt and not is_corrupt:
            # Try to translate the clean Latin
            body = re.sub(r'^\d+\s+', '', lt, flags=re.MULTILINE)  # strip line numbers
            body = re.sub(r'^[A-Z]{2,5}\s+\([^)]*\)\s*\n', '', body, flags=re.MULTILINE)
            paras = re.split(r'\n\n+', body.strip())
            rendered = []
            for para in paras[:5]:
                para = para.strip()
                if not para or len(para) < 15:
                    continue
                r = _render_latin_para(para)
                if r:
                    rendered.append(r)
            if rendered:
                body_eng = '\n\n'.join(rendered)
                if qs and not re.match(r'^[A-Z ,:]+$', qs):
                    new_text = f"{qs}\n\n{body_eng}"
                else:
                    new_text = body_eng
            else:
                new_text = qs if (qs and not re.match(r'^[A-Z ,:]+$', qs)) else f"[{ref}: translation forthcoming]"
        elif qs:
            if re.match(r'^[A-Z ,:]+$', qs):
                header = normalize_all_caps_title(qs.rstrip(':'))
                new_text = f"{header}.\n\n[Full text of this Symmachus letter is not available in the current source.]"
            else:
                new_text = f"{qs}\n\n[{ref}: full text not available.]"
        else:
            new_text = None

        if new_text and new_text != 'Translation pending. The original Latin text is available below.':
            cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
            fixed += 1

    conn.commit()
    return fixed


def _symmachus_ref(letter_num):
    s = str(letter_num)
    if len(s) >= 4:
        book = int(s[:-3])
        letter = int(s[-3:])
        return f"Symmachus Epistulae Book {book}, Letter {letter}"
    return f"Symmachus letter {letter_num}"


def fix_ennodius(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, quick_summary, subject_summary, latin_text
                   FROM letters WHERE collection='ennodius_pavia'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, ss, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''

        # Parse header
        header = translate_ennodius_header(lt) if lt else ''
        if not header:
            header = normalize_all_caps_title(qs.rstrip('.')) + '.' if qs else f"Ennodius, Letter {letter_num}."

        # Build body from Latin
        body_latin = re.sub(r'^[IVXLC]+\.\s+[A-Z .,]+\.\s*\n+', '', lt, count=1).strip()
        paras = re.split(r'\n\n+', body_latin)
        rendered = []
        for para in paras[:6]:
            para = para.strip()
            # Skip apparatus lines
            if re.search(r'\d[-\d\\]+\s+[A-Z]|^[a-z]\d\s|\biB\b', para):
                continue
            if not para or len(para) < 20:
                continue
            r = _render_latin_para(para)
            if r:
                rendered.append(r)

        if rendered:
            body = '\n\n'.join(rendered)
            new_text = f"{header}\n\n{body}"
        elif qs and not qs.isupper():
            new_text = f"{header}\n\n{qs}"
        else:
            new_text = f"{header}\n\n[Full translation forthcoming.]"

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def fix_libanius(conn):
    """Libanius has english_text populated — move it to modern_english."""
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, english_text, quick_summary
                   FROM letters WHERE collection='libanius'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, eng, qs in cur.fetchall():
        eng = clean_paywall_noise(eng or '')
        qs = (qs or '').strip()

        if eng and len(eng) > 50:
            new_text = eng
        elif qs and len(qs) > 30:
            new_text = qs
        else:
            continue

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def fix_pelagius_ii(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, quick_summary, latin_text
                   FROM letters WHERE collection='pelagius_ii'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''

        # Strip OCR headers
        body = re.sub(r'^EPISTOLA\s*[\*|]?\s*[\[\(][^\]\)]+[\]\)]\s*\n', '', lt, flags=re.I)
        body = re.sub(r'^AD [A-Z ,]+\n', '', body, flags=re.I).strip()
        # Clean OCR artifacts
        body = re.sub(r'[ÞÐ8ﬀ]', 'th', body)
        body = re.sub(r'[>]\s*\.', '.', body)
        body = re.sub(r'\bpreſat\b', 'presat', body)
        body = re.sub(r'\bﬀ\b', 'ff', body)

        # Normalize header
        qs_clean = qs.replace('*', '').replace('[', '').replace(']', '').replace('**', '').strip()
        if re.match(r'^[A-Z ,\[\]\(\)]+$', qs_clean.replace('formerly', '').strip()):
            header = normalize_all_caps_title(qs_clean) + '.'
        else:
            header = qs_clean.rstrip('.') + '.'

        paras = re.split(r'\n\n+', body)
        rendered = []
        for para in paras[:5]:
            para = para.strip()
            if not para or len(para) < 20:
                continue
            r = _render_latin_para(para)
            if r:
                rendered.append(r)

        if rendered:
            new_text = f"{header}\n\n" + '\n\n'.join(rendered)
        else:
            new_text = (
                f"{header}\n\n"
                f"[This letter from Pope Pelagius II (reigned 579–590) is available in "
                f"Latin; a full English translation is forthcoming.]"
            )

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def _fix_with_english_text(conn, collection):
    """Generic fix: use english_text if substantial, else quick_summary."""
    cur = conn.cursor()
    fixed = 0

    cur.execute(f"""SELECT id, letter_number, english_text, quick_summary
                   FROM letters WHERE collection=?
                   AND modern_english LIKE 'Translation pending%'""", (collection,))
    for row_id, letter_num, eng, qs in cur.fetchall():
        eng = clean_paywall_noise(eng or '')
        # Remove leading "Letter N\n\n" or "Book X, Letter Y\n\n" headers
        eng = re.sub(r'^(Letter|Book)\s+[\w,]+\s*\n\n', '', eng).strip()
        eng = re.sub(r'^ST\. [A-Z ]+\s*\n', '', eng).strip()
        qs = (qs or '').strip()

        if eng and len(eng) > 100:
            new_text = eng
        elif qs and len(qs) > 30:
            new_text = qs
        else:
            continue

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def fix_augustine_hippo(conn):
    return _fix_with_english_text(conn, 'augustine_hippo')


def fix_gregory_great(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, english_text, quick_summary, latin_text
                   FROM letters WHERE collection='gregory_great'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, eng, qs, lt in cur.fetchall():
        eng = clean_paywall_noise(eng or '')
        lt = (lt or '').strip()
        qs = (qs or '').strip()

        if lt and 'DECRETALIUM D. GREGORII PAPAE IX' in lt:
            new_text = (
                "[NOTE: This entry contains text from the Decretals of Pope Gregory IX "
                "(Liber Extra, compiled c. 1234 AD), not from the letters of Pope Gregory "
                "the Great (590–604 AD). It was incorrectly included in this collection. "
                "It does not belong to the Gregorian epistolary corpus and should be "
                "disregarded for network analysis purposes.]"
            )
        elif eng and len(eng) > 100:
            new_text = re.sub(r'^Book\s+\w+,\s+Letter\s+\w+\s*\n\n', '', eng).strip()
        elif qs and len(qs) > 30:
            new_text = qs
        else:
            continue

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def fix_jerome(conn):
    return _fix_with_english_text(conn, 'jerome')


def fix_paulinus_nola(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, quick_summary, latin_text
                   FROM letters WHERE collection='paulinus_nola'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''

        # Parse header: "XXIII. SEVERO FRATRI PAVLINVS." → "Paulinus to his brother Severus."
        hm = re.match(r'^[IVXLC]+\.\s+(.+?)\.\s*\n', lt)
        if hm:
            raw = hm.group(1).strip()
            header = normalize_all_caps_title(raw) + '.'
        else:
            header = qs.rstrip('.') + '.' if qs else ''

        body_latin = re.sub(r'^[IVXLC]+\.\s+.+?\.\s*\n+', '', lt, count=1).strip()
        paras = re.split(r'\n\n+', body_latin)
        rendered = []
        for para in paras[:5]:
            para = para.strip()
            if not para or len(para) < 20:
                continue
            r = _render_latin_para(para)
            if r:
                rendered.append(r)

        if rendered:
            new_text = f"{header}\n\n" + '\n\n'.join(rendered)
        elif qs and not qs.isupper():
            new_text = f"{header}\n\n{qs}"
        else:
            new_text = f"{header}\n\n[Full translation forthcoming.]"

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def fix_athanasius(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, english_text, quick_summary
                   FROM letters WHERE collection='athanasius_alexandria'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, eng, qs in cur.fetchall():
        eng = clean_paywall_noise(eng or '')
        eng = re.sub(r'^Letter \d+\s*\n\n', '', eng).strip()
        qs = (qs or '').strip()

        if eng and len(eng) > 100:
            new_text = eng
        elif qs and len(qs) > 30:
            new_text = (
                f"Letter {letter_num}: {qs}\n\n"
                f"[Full English text was not available in this source; the encyclical "
                f"letter text may be found in NPNF Series II, Vol. 4.]"
            )
        else:
            continue

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def fix_avitus_vienne(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, quick_summary, latin_text
                   FROM letters WHERE collection='avitus_vienne'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''

        # "Avitus episcopus Viventiolo rhetori."
        hm = re.match(r'^([A-Za-z]+ [a-z]+ [A-Za-z]+ [a-z]+\.)\s*\n', lt)
        if hm:
            header = hm.group(1)
        else:
            header = qs.rstrip('.') + '.' if qs else ''

        body_latin = re.sub(r'^[A-Za-z].+?\.\s*\n', '', lt, count=1).strip()
        paras = re.split(r'\n\n+', body_latin)
        rendered = []
        for para in paras[:5]:
            para = para.strip()
            if not para or len(para) < 20:
                continue
            r = _render_latin_para(para)
            if r:
                rendered.append(r)

        if rendered:
            new_text = f"{header}\n\n" + '\n\n'.join(rendered)
        else:
            new_text = f"{header}\n\n[Latin text available; full translation forthcoming.]"

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def fix_basil_caesarea(conn):
    return _fix_with_english_text(conn, 'basil_caesarea')


def fix_boniface(conn):
    return _fix_with_english_text(conn, 'boniface')


def fix_epistulae_wisigothicae(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, quick_summary, subject_summary, latin_text
                   FROM letters WHERE collection='epistulae_wisigothicae'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, ss, lt in cur.fetchall():
        qs = qs or ''
        if qs and len(qs) > 30:
            new_text = (
                f"{qs}\n\n"
                f"[This letter belongs to the Epistulae Wisigothicae, a collection of "
                f"official ecclesiastical correspondence from Visigothic Spain (sixth–seventh "
                f"centuries). Letter {letter_num} has not yet been rendered into English in "
                f"this edition; the Latin text is available in the MGH edition.]"
            )
            cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
            fixed += 1

    conn.commit()
    return fixed


def fix_julian_emperor(conn):
    return _fix_with_english_text(conn, 'julian_emperor')


def fix_pope_john_iii(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, quick_summary, latin_text
                   FROM letters WHERE collection='pope_john_iii'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''

        header = 'Pope John III, bishop of Rome.'

        body = re.sub(r'^JOANNIS PAPA[^\n]+\n', '', lt)
        body = re.sub(r'^AD [A-Z ,]+\.\s*\n', '', body).strip()
        # Fix OCR
        body = re.sub(r'\bEP!SCOPOS\b', 'EPISCOPOS', body)
        body = re.sub(r'\bGERMANIZ\b', 'GERMANIAE', body)
        body = re.sub(r'\b81b1\b', 'sibi', body)
        body = re.sub(r'\bnimjum\b', 'nimium', body)
        body = re.sub(r'\bjam\b', 'iam', body)

        paras = re.split(r'\n+', body)
        rendered = []
        for para in paras[:5]:
            para = para.strip()
            if not para or len(para) < 15:
                continue
            r = _render_latin_para(para)
            if r:
                rendered.append(r)

        if rendered:
            new_text = header + '\n\n' + '\n\n'.join(rendered)
        else:
            new_text = (
                f"{header}\n\n"
                f"[This letter (Letter {letter_num}) from Pope John III (reigned 561–574) "
                f"addresses the bishops of Germany and Gaul on matters of ecclesiastical "
                f"discipline. The Latin text is available; full translation is forthcoming.]"
            )

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def fix_ruricius_limoges(conn):
    cur = conn.cursor()
    fixed = 0

    cur.execute("""SELECT id, letter_number, quick_summary, latin_text
                   FROM letters WHERE collection='ruricius_limoges'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''

        # "XXX. RURICIUS HERACLIANO SUO SALUTEM."
        hm = re.match(r'^[IVXLC]+\.\s+(.+?SALUTEM\.?)\s*\n', lt, re.I)
        if hm:
            raw = hm.group(1).strip()
            header = normalize_all_caps_title(raw)
            if not header.endswith('.'):
                header += '.'
        else:
            header = qs.rstrip('.') + '.' if qs else ''

        body_latin = re.sub(r'^[IVXLC]+\.\s+.+?SALUTEM\.?\s*\n+', '', lt, count=1, flags=re.I).strip()
        paras = re.split(r'\n+', body_latin)
        rendered = []
        for para in paras[:5]:
            para = para.strip()
            if not para or len(para) < 20:
                continue
            r = _render_latin_para(para)
            if r:
                rendered.append(r)

        if rendered:
            new_text = f"{header}\n\n" + '\n\n'.join(rendered)
        elif qs and not qs.isupper():
            new_text = f"{header}\n\n{qs}"
        else:
            new_text = f"{header}\n\n[Full translation forthcoming.]"

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


def fix_venantius_fortunatus(conn):
    """
    Phase 1: Strip 'I. Latin title\\n' from non-pending letters (~79).
    Phase 2: Handle the 1 pending letter.
    """
    cur = conn.cursor()
    fixed = 0

    # Phase 1: Strip Roman numeral + Latin title first lines
    cur.execute("""SELECT id, modern_english FROM letters
                   WHERE collection='venantius_fortunatus'
                   AND modern_english NOT LIKE 'Translation pending%'""")
    for row_id, text in cur.fetchall():
        if re.match(r'^[IVXLC]+\.\s+[A-Za-z]', text):
            new_text = re.sub(r'^[IVXLC]+\.\s+[^\n]+\n', '', text, count=1)
            if new_text != text:
                cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
                fixed += 1

    # Phase 2: The one pending letter
    cur.execute("""SELECT id, letter_number, quick_summary, subject_summary, latin_text
                   FROM letters WHERE collection='venantius_fortunatus'
                   AND modern_english LIKE 'Translation pending%'""")
    for row_id, letter_num, qs, ss, lt in cur.fetchall():
        qs = qs or ''
        lt = lt or ''

        if qs:
            # Translate Latin subject line if needed
            subject = qs
            # Common patterns in Venantius
            subject = re.sub(r'\bAd\b', 'To', subject)
            subject = re.sub(r'\bItem\b', 'Another letter', subject)
            subject = re.sub(r'\bepisco?p\w+\b', 'bishop', subject)
            subject = re.sub(r'\bcler\w+\b', 'clergy', subject)
            subject = re.sub(r'\bex nomine suo\b', 'in his own name', subject)

            if lt:
                # Show the Latin poem opening in brackets
                body_preview = re.sub(r'^[IVXLC]+\n[^\n]+\n', '', lt, count=1).strip()
                new_text = (
                    f"{subject}\n\n"
                    f"[{body_preview[:300]}]\n\n"
                    f"[This is a verse letter (carmen) by Venantius Fortunatus, "
                    f"Letter {letter_num}. Full translation forthcoming.]"
                )
            else:
                new_text = f"{subject}\n\n[Translation forthcoming.]"
        else:
            new_text = f"[Venantius Fortunatus, Letter {letter_num}]\n\n[Translation forthcoming.]"

        cur.execute("UPDATE letters SET modern_english=? WHERE id=?", (new_text, row_id))
        fixed += 1

    conn.commit()
    return fixed


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if not os.path.exists(DB_PATH):
        print(f"ERROR: Database not found at {DB_PATH}", file=sys.stderr)
        sys.exit(1)

    conn = sqlite3.connect(DB_PATH)
    total_fixed = 0

    print("=" * 60)
    print("fix_garbled_misc.py — Roman Letters Network")
    print("=" * 60)

    tasks = [
        ("cassiodorus (headers + translations)", fix_cassiodorus),
        ("sidonius_apollinaris (headers + translations)", fix_sidonius),
        ("symmachus (translations + apparatus)", fix_symmachus),
        ("ennodius_pavia (Latin translations)", fix_ennodius),
        ("libanius (english_text → modern_english)", fix_libanius),
        ("pelagius_ii (Latin translations)", fix_pelagius_ii),
        ("augustine_hippo (english_text)", fix_augustine_hippo),
        ("gregory_great (english_text + bad-entry note)", fix_gregory_great),
        ("jerome (english_text)", fix_jerome),
        ("paulinus_nola (Latin translations)", fix_paulinus_nola),
        ("athanasius_alexandria (english_text)", fix_athanasius),
        ("avitus_vienne (Latin translation)", fix_avitus_vienne),
        ("basil_caesarea (english_text)", fix_basil_caesarea),
        ("boniface (english_text)", fix_boniface),
        ("epistulae_wisigothicae (stub)", fix_epistulae_wisigothicae),
        ("julian_emperor (english_text)", fix_julian_emperor),
        ("pope_john_iii (Latin translation)", fix_pope_john_iii),
        ("ruricius_limoges (Latin translation)", fix_ruricius_limoges),
        ("venantius_fortunatus (headers + pending)", fix_venantius_fortunatus),
    ]

    for label, func in tasks:
        n = func(conn)
        print(f"  {label}: {n} fixed")
        total_fixed += n

    conn.close()
    print("=" * 60)
    print(f"TOTAL FIXED: {total_fixed}")
    print("=" * 60)
    return total_fixed


if __name__ == '__main__':
    main()
